-- CREATE USER 'project1240'@'127.0.0.1' IDENTIFIED BY 'oaTx8H034ChsAj6k';

-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW ON *.* TO 'project1240'@'127.0.0.1';

-- GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `project1240`.* TO 'project1240'@'127.0.0.1';

-- GRANT GRANT OPTION ON `project1240`.* TO 'project1240'@'127.0.0.1';


CREATE USER 'project1240'@'127.0.0.1' IDENTIFIED BY 'oaTx8H034ChsAj6k';
GRANT SELECT, INSERT, UPDATE, DELETE, FILE, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'project1240'@'127.0.0.1' IDENTIFIED BY 'oaTx8H034ChsAj6k' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;